# -*- coding: utf-8 -*-
"""NER:NamedEntityRecognition(usingSpaCy).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQ4DdQJOUlxyL_tnmyhr1beO10KXEfK2
"""

!pip install -U Spacy
!python -m spacy download en_core_web_sm

import spacy

# Load English model
nlp = spacy.load("en_core_web_sm")

text = "Apple is opening a new office in Paris in 2025."

# Process the text
doc = nlp(text)

# Print entities
for ent in doc.ents:
    print(ent.text, ent.label_)

# In short: NER finds the “who, what, where, when” in your text and labels them.

text="IIUM professor doubles down: 'Romans learned shipbuilding from Malays' theory based on extensive study"

doc = nlp(text)
for ent in doc.ents:
    print(f'Text: {ent.text},Label: {ent.label_},Explanation: {spacy.explain(ent.label_)}\n')

from spacy import displacy
displacy.render(doc, style="ent", jupyter=True)

corpus = [
    "Barack Obama visited Kuala Lumpur on 10th November 2025 to attend the UN conference.",
    "Apple Inc. announced the release of the new iPhone 15, priced at $999, at their headquarters in Cupertino.",
    "The Eiffel Tower is one of the most famous landmarks in Paris.",
    "Python and Java are popular programming languages used in AI and data science projects.",
    "The company achieved a 25% increase in revenue this quarter.",
    "The World Cup 2026 will be held in multiple cities across the USA, Canada, and Mexico.",
    "The Malaysian Parliament passed the new Data Protection Act yesterday.",
    "Tesla's new Model S Plaid can reach 0-60 mph in less than 2 seconds.",
    "The Olympics opening ceremony will start at 8:00 PM local time.",
    "Harvard University and MIT are renowned educational institutions in the USA."
]

# Named Entity Recognition (NER) on a corpus
for text in corpus:
    # Process each document with spaCy NLP pipeline
    doc = nlp(text)

    # Display the original text
    print(f'\nText: {text}')

    # Loop through detected named entities and display them
    for ent in doc.ents:
        print(f'{ent.text} -> {ent.label_}')

